project_id = "ffndxwyviafznftdxnib"

[functions.webhook-create-epi]
verify_jwt = false

[functions.signup-onboarding]
verify_jwt = false

[functions.whatsapp-proxy]
verify_jwt = false

[functions.check-epi-vencidos]
verify_jwt = false
