import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
      },
      colors: {
        primary: {
          50: "#E6EEF7",
          100: "#CCE0F2",
          200: "#99C0E5",
          300: "#4D8BC8",
          400: "#0E4174",
          500: "#00378A",
          600: "#002D70",
          700: "#002358",
          800: "#001A40",
          900: "#001029",
          DEFAULT: "#00378A",
          foreground: "#FFFFFF",
        },
        secondary: {
          50: "#E6F5FA",
          100: "#B3E0F0",
          200: "#80CCE6",
          300: "#4DB8DB",
          400: "#0082B8",
          500: "#006E9C",
          600: "#005A80",
          700: "#004664",
          800: "#003248",
          900: "#001E2C",
          DEFAULT: "#0082B8",
          foreground: "#FFFFFF",
        },
        accent: { DEFAULT: "#0E4377", foreground: "#FFFFFF" },
        background: "#F7FBFF",
        foreground: "#221E1E",
        card: { DEFAULT: "#FFFFFF", foreground: "#221E1E" },
        popover: { DEFAULT: "#FFFFFF", foreground: "#221E1E" },
        muted: { DEFAULT: "#F1F5F9", foreground: "#6F8CAA" },
        border: "#E2E8F0",
        input: "#E2E8F0",
        ring: "#0082B8",
        destructive: { DEFAULT: "#DC2626", foreground: "#FFFFFF" },
        success: { DEFAULT: "#059669", foreground: "#FFFFFF" },
        warning: { DEFAULT: "#D97706", foreground: "#FFFFFF" },
        info: { DEFAULT: "#0082B8", foreground: "#FFFFFF" },
        sidebar: {
          DEFAULT: "#00378A",
          foreground: "#FFFFFF",
          primary: "#0082B8",
          "primary-foreground": "#FFFFFF",
          accent: "#0E4174",
          "accent-foreground": "#FFFFFF",
          border: "rgba(255,255,255,0.08)",
          ring: "#0082B8",
        },
        chart: {
          1: "#00378A",
          2: "#0082B8",
          3: "#0E4174",
          4: "#6F8CAA",
          5: "#059669",
        },
      },
      borderRadius: { lg: "12px", md: "8px", sm: "6px", xl: "16px" },
      boxShadow: {
        card: "0 1px 3px 0 rgba(0,55,138,0.05), 0 1px 2px -1px rgba(0,55,138,0.04)",
        "card-hover": "0 8px 24px -4px rgba(0,55,138,0.10)",
        elevated: "0 12px 32px -8px rgba(0,55,138,0.12)",
        "inner-glow": "inset 0 1px 0 0 rgba(255,255,255,0.05)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "slide-in-right": {
          "0%": { opacity: "0", transform: "translateX(12px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        counter: {
          "0%": { opacity: "0", transform: "translateY(4px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in-up": "fade-in-up 0.4s ease-out forwards",
        "scale-in": "scale-in 0.3s ease-out forwards",
        "slide-in-right": "slide-in-right 0.3s ease-out forwards",
        counter: "counter 0.5s ease-out forwards",
        shimmer: "shimmer 2s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
